<?php

use Tigren\Testimonial\Block\Adminhtml\AssignCustomer;

/** @var  Tigren\Testimonial\Block\Adminhtml\AssignCustomer $block */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<!--<input type="hidden" name="rh_customers" data-form-part="custom_form" id="rh_customers" value=""/>-->
<script type="text/x-magento-init">
    {
        "*": {
            "Tigren_Testimonial/js/assign-customer": {
                "selectedCustomers": <?= /* @escapeNotVerified */
    $block->getCustomerJson() ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */
    '"' . $gridJsObjectName . '"' ?: '{}' ?>
    }
}
}
</script>
<script>
    require('mage/apply/main').apply();
</script>
