<div data-mage-init='{"Tigren_Testimonial/js/path/to/customJs1":{
    "message" : "hello khanh nhu nguyen"
    }}'>
</div>
<!--<script>-->
<!--    require(['Tigren_Testimonial::js/path/to/customJs1'], function (customJs1) {-->
<!--        // Lấy đối tượng config từ phần tử chứa data-mage-init-->
<!--        var config = JSON.parse(document.querySelector('[data-mage-init]').getAttribute('data-mage-init'));-->
<!---->
<!--        // Gọi customJs với config lấy từ data-mage-init-->
<!--        customJs1(config.customJs1);-->
<!--    });-->
<!--</script>-->
