<?php

use Magento\Customer\Model\SessionFactory;


/** @var  \Tigren\CustomerGroupCatalog\Block\RuleList $block */
const URL_RULE = "http://magento246.com/rule/rule/";
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>List Rule</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <style>
        .flex {
            display: flex;
            align-items: center;
            gap: 10px;
            border: 1px solid #a29f9f;
            padding: 5px;
            border-radius: 5px;
            color: black;
            margin-bottom: 5px;
        }

        table {
            width: 100%;
        }
    </style>
</head>
<body>
<h3>History</h3>
<span><?= $block->getCustomerSession() ?></span>
<table>
    <thead>
    <tr>
        <th>Order</th>
        <th>Rule</th>
        <th>Time Order</th>
    </tr>
    </thead>
    <tbody>
    <?php

    if ($block->getRuleItem() != null):
        foreach ($block->getRuleItem() as $value): ?>
            <tr>
                <td><a href=""><?= $value->getEntityId() ?>  </a></td>
                <td><a href=""><?= $value->getOrderId() ?> </a></td>
                <td><a href=""><?= $value->getCustomerId() ?>  </a></td>
                <td><a href=""><?= $value->getRuleId() ?></a></td>
                <td><?= date($value->getCreatedAt()) ?></td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
    </tbody>
</table>
<?php //foreach ($block->getRuleItem() as $value): ?>
<!--    <a href="" class="flex">-->
<!--        <div class="group">-->
<!--            Order Code: --><?php //= $value->getOrderId() ?>
<!--        </div>-->
<!--        <div class="group">-->
<!--            Discount: --><?php //= $value->getRuleId() ?>
<!--        </div>-->
<!--        <div class="group">-->
<!--            Time: --><?php //= $value->getCreatedAt() ?>
<!--        </div>-->
<!--    </a>-->
<?php //endforeach; ?>
</body>
</html>

